Renaming scaler keyword arguments in PLS classes Calling any function relying on `sklearn.base.BaseEstimator.get_params()` for any of the PLS classes currently results in an attribute error (see below). Examples include `self.__repr__()`, invoked by via `ChemometricsPLS()`.
This behavior is caused by the values passed as keyword arguments xscaler and yscaler being assigned to attributes x_scaler, y_scaler, respectively. As `BaseEstimator.get_params()` expects all keyword arguments to be stored as attributes with the same name, an AttributeError is raised.

Current behaviour:
```python
> ChemometricsPLS().get_params()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[97], line 2
      1 _pls = ChemometricsPLS()
----> 2 _pls.get_params()

File ~\AppData\Local\miniconda3\envs\pyChemometrics\Lib\site-packages\sklearn\base.py:194, in BaseEstimator.get_params(self, deep)
    192 out = dict()
    193 for key in self._get_param_names():
--> 194     value = getattr(self, key)
    195     if deep and hasattr(value, "get_params") and not isinstance(value, type):
    196         deep_items = value.get_params().items()

AttributeError: 'ChemometricsPLS' object has no attribute 'xscaler'
```

Expected behavior:
```python
> ChemometricsPLS().get_params()

{'ncomps': 2, 'pls_algorithm__copy': True, 'pls_algorithm__max_iter': 500, 'pls_algorithm__n_components': 2, 'pls_algorithm__scale': False, 'pls_algorithm__tol': 1e-06, 'pls_algorithm': PLSRegression(scale=False), 'x_scaler__copy': True, 'x_scaler__scale_power': 1, 'x_scaler__with_mean': True, 'x_scaler__with_std': True, 'x_scaler': ChemometricsScaler(), 'y_scaler__copy': True, 'y_scaler__scale_power': 0, 'y_scaler__with_mean': True, 'y_scaler__with_std': False, 'y_scaler': ChemometricsScaler(scale_power=0, with_std=False)}
```